import {test,expect} from '@playwright/test';
import {createHash} from 'node:crypto';
import {login} from './fixtures/session.mjs';
const data=Buffer.from('isolated firmware');
const artifact={id:'mqtt',filename:'amebapro2_mqtt_flash_ntz.bin',size_bytes:data.length,sha256:createHash('sha256').update(data).digest('hex'),kind:'firmware'};
const catalog={schema:'rtk-pro2-examples/v1',test_only:true,version:'v1',source_commit:'a'.repeat(40),terms_version:'eval-v1',terms:'Evaluation only.',dependencies:{sdk:'9.6e'},artifacts:[{...artifact,id:'source',kind:'source'},...['mqtt','webrtc_test_video','webrtc_camera'].flatMap(id=>[{...artifact,id},{...artifact,id:id+'-sha',kind:'checksum'}])],examples:['mqtt','webrtc_test_video','webrtc_camera'].map(id=>({id,title:id,description:'Evaluation example',board:'PRO2',sensor:'GC2053',image_type:'full-flash-ntz',flash_offset:0,firmware_id:id,checksum_id:id+'-sha',validation:{build:'PASS',hardware:'NOT_RUN'}}))};
test('[UI-CA-PRO2-001] PRO2 official URL firmware and local selection @smoke',async({page},testInfo)=>{
 await page.addInitScript(()=>{let reader;const port={async open(){this.readable=new ReadableStream({start(c){reader=c}});this.writable=new WritableStream({write(){}})},async close(){try{reader.close()}catch{}},async setSignals(){}};Object.defineProperty(navigator,'serial',{value:{addEventListener(){},removeEventListener(){},requestPort:async()=>port},configurable:true})});
 await login(page,'developer');
 await page.route('**/api/developer/pro2-examples/catalog?*',r=>r.fulfill({json:catalog}));
 await page.route('**/api/developer/pro2-examples/download',r=>r.fulfill({json:{url:'https://objects.example/test.bin',artifact}}));
 await page.route('https://objects.example/test.bin',r=>r.fulfill({body:data,headers:{'access-control-allow-origin':'*'}}));
 await page.route('**/api/developer/pro2-examples/catalog?*',r=>r.fulfill({json:{version:'v1'}}),{times:1});
 await page.goto('/console/chipset-sdk/pro2/cloud-examples');
 await expect(page.getByRole('alert')).toContainText('unavailable');
 await page.getByRole('button',{name:'Reload release'}).click();
 await expect(page.getByRole('heading',{name:'Cloud Examples',exact:true})).toBeVisible();
 await expect(page.getByRole('link',{name:'Burn this example'})).toHaveCount(3);
 await page.screenshot({path:`/tmp/pro2-examples-${testInfo.project.name}.png`,fullPage:true});
 await page.getByRole('link',{name:'Burn this example'}).first().click();
 await page.getByLabel('I accept these evaluation terms.').check();
 await page.getByRole('button',{name:'Download / retry firmware'}).click();
 await expect(page.getByText('Downloaded and SHA-256 verified.',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Connect UART',exact:true}).click();
 await page.getByRole('button',{name:'Burn firmware',exact:true}).click();
 await expect(page.locator('#burn')).toBeEnabled();
 await expect(page.locator('#file-info')).toContainText(artifact.filename);
 await page.locator('#firmware').setInputFiles({name:'local.bin',mimeType:'application/octet-stream',buffer:Buffer.from('local')});
 await expect(page.locator('#file-info')).toContainText('local.bin');
 await expect(page.locator('#burn')).toBeEnabled();
 await page.route('https://objects.example/test.bin',r=>r.fulfill({body:Buffer.alloc(data.length),headers:{'access-control-allow-origin':'*'}}));
 await page.getByRole('button',{name:'Download / retry firmware'}).click();
 await expect(page.getByRole('alert')).toContainText('SHA-256 mismatch');
 await expect(page.locator('#burn')).toBeDisabled();
});
