import { test, expect } from './fixtures/scoped-products.mjs';
import { readFile } from 'node:fs/promises';

const cloud='11111111-1111-4111-8111-111111111111', product='33333333-3333-4333-8333-333333333333', device='77777777-7777-4777-8777-000000000000';
test('[UI-CA-TESTLAB-001] Console lab preserves scope and distinguishes local checks from live tests @smoke',async({page,request},info)=>{
  expect((await request.post('/__fixture__/reset')).ok()).toBeTruthy();
  let liveWrites=0, creations=0, runtimeReady=false;
  const bundle={identity:{id:device},key:{material:{private_key_pem:'fixture-private-key'}},certificate:{chain_pem:['fixture-certificate']}};
  await page.route('**/api/developer/test-device-batches',route=>{creations++;return route.fulfill({contentType:'application/vnd.realtek.rtk-certificate-bundle+json',body:JSON.stringify(bundle)});});
  const account='88888888-8888-4888-8888-888888888888';let bound=false, provisioned=false, claims=0;
  page.on('dialog',dialog=>dialog.accept());
  await page.route('**/test-lab/manage/**',async route=>{
    const req=route.request(), url=new URL(req.url());
    if(url.pathname.endsWith('/accounts'))return route.fulfill({json:{id:account,email:'lab@example.test'}});
    if(req.method()==='GET')return route.fulfill({json:{devices:[{id:device,name:'Test camera',bound,bindable:!bound,provision_status:provisioned?'activated':'not_provisioned',connection_status:'offline'}],has_more:false,next_offset:1}});
    const body=req.postDataJSON();expect(body.account_id).toBe(account);expect(body.product_id).toBe(product);
    if(url.pathname.endsWith('/grant')){claims++;return route.fulfill({json:{claim_token:'f'.repeat(64)}});}
    if(url.pathname.endsWith('/bind')){expect(body.claim_token).toBe('f'.repeat(64));bound=true;}
    if(url.pathname.endsWith('/unbind'))bound=false;
    if(url.pathname.endsWith('/provision')){expect(body.clip_public_key).toContain('BEGIN PUBLIC KEY');provisioned=true;}
    return route.fulfill({json:{status:'completed'}});
  });
  // The Product fixture does not implement legacy fleet telemetry. Stub only
  // that unrelated surface so navigation is not redirected by a fixture 401.
  await page.route('**/api/developer/brand-clouds/*/fleet/**',route=>route.fulfill({json:{devices:[],source:{status:'unavailable'}}}));
  await page.route('**/test-lab/context?**',route=>route.fulfill({json:{environment:'dev',brand_cloud_id:cloud,product_id:product,device_id:device,devid:'camera-1',device_status:'registered',runtime_ready:runtimeReady,blocked_reason:'runtime_authorization_unavailable',capabilities:{mqtt:true,shadow_http:true,shadow_mqtt:true,webrtc:true}}}));
  await page.route('**/test-lab/sessions**',route=>{liveWrites++;return route.fulfill({status:503});});
  // Enter through the legacy overview shell, not only a direct feature URL.
  await page.goto(`/console/clouds/${cloud}`);
  const menu = page.getByRole('button',{name:'Open navigation',exact:true});
  if (await menu.isVisible()) await menu.click();
  await page.getByRole('link',{name:'Cloud Test Lab',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Cloud Test Lab',exact:true}).first()).toBeVisible();
  await expect(page.locator('#test-lab-product-id')).toHaveCount(0);
  await expect(page.getByRole('button',{name:/^(Previous|Next) (Products|devices)$/i})).toHaveCount(0);
  const productOption = page.getByRole('combobox',{name:'Product',exact:true}).locator(`option[value="${product}"]`);
  await expect(productOption).not.toHaveText(product);
  await expect(productOption).not.toHaveText('Unnamed Product');
  await page.getByRole('combobox',{name:'Product',exact:true}).selectOption(product);
  await expect(page.locator('#test-lab-product-id')).toContainText(product);
  await expect(productOption).toHaveText('Camera 00');
  await page.goto(`/console/clouds/${cloud}/test-lab?product_id=${product}&device_id=${device}`);
  const panel=page.getByTestId('test-lab');
  await expect(panel.getByRole('button',{name:'Authorize account',exact:true})).toHaveCount(0);
  await expect(panel.getByRole('textbox',{name:'Test account password'})).toHaveCount(0);
  await expect(panel).toContainText('using your Console login');
  await expect(panel).toContainText('No bound test devices');
  const createTrigger = panel.getByRole('button',{name:'Create test device',exact:true});
  await createTrigger.click();
  const confirmation = panel.getByRole('alertdialog',{name:'Confirm test action'});
  await expect(confirmation).toBeVisible();
  for (let index = 0; index < 5; index++) {
    await page.keyboard.press('Tab');
    expect(await confirmation.evaluate(element => element.contains(document.activeElement))).toBeTruthy();
  }
  await page.keyboard.press('Escape');
  await expect(confirmation).toHaveCount(0);
  await expect(createTrigger).toBeFocused();
  expect(creations).toBe(0);
  await panel.getByRole('button',{name:'Create test device',exact:true}).click();
  await panel.getByRole('button',{name:'Continue',exact:true}).click();
  const credentials=panel.getByRole('region',{name:'Device credentials ready'});
  await expect(credentials).toContainText('not yet confirmed saved');
  const credentialLink=credentials.getByRole('link',{name:'Download device credentials',exact:true});
  await expect(credentialLink).toBeVisible();
  const credentialURL=await credentialLink.getAttribute('href');
  // The old implementation revoked this URL after one second.
  await page.waitForTimeout(1500);
  for(let attempt=0;attempt<2;attempt++) {
    const pending=page.waitForEvent('download');await credentialLink.click();const downloaded=await pending;
    expect(downloaded.suggestedFilename()).toBe(`rtk-test-device-${device}.json`);
    expect(await downloaded.failure()).toBeNull();
    expect(JSON.parse(await readFile(await downloaded.path(),'utf8'))).toEqual(bundle);
    expect(await credentialLink.getAttribute('href')).toBe(credentialURL);
  }
  expect(creations).toBe(1);
  await expect(credentials).toContainText('cannot confirm that the file was saved');
  await credentials.getByRole('checkbox',{name:'I have saved this file securely'}).check();
  await panel.getByRole('button',{name:'Bind device',exact:true}).click();
  await panel.getByRole('combobox',{name:'Unbound test device'}).selectOption(device);
  await panel.getByRole('button',{name:'Confirm bind',exact:true}).click();
  await panel.getByRole('alertdialog',{name:'Confirm test action'}).getByRole('button',{name:'Continue',exact:true}).click();
  await expect(panel.getByRole('button',{name:'Unbind',exact:true})).toBeVisible();
  await panel.getByRole('button',{name:'Provision',exact:true}).click();
  await panel.getByRole('button',{name:'Generate and download test key',exact:true}).click();
  const provisionDownload=panel.getByRole('region',{name:'Provision key ready'});
  const keyDownload=page.waitForEvent('download');
  await provisionDownload.getByRole('link',{name:'Download provision key',exact:true}).click();
  const keyFile=await keyDownload;
  expect(keyFile.suggestedFilename()).toContain(`test-provision-${device}-`);
  const keyBundle=JSON.parse(await readFile(await keyFile.path(),'utf8'));
  expect(keyBundle.device_id).toBe(device);
  expect(keyBundle.clip_private_key).toContain('BEGIN PRIVATE KEY');
  expect(keyBundle.clip_public_key).toContain('BEGIN PUBLIC KEY');
  await provisionDownload.getByRole('checkbox',{name:'I have saved this file securely'}).check();
  await panel.getByRole('button',{name:'Start provision',exact:true}).click();
  await panel.getByRole('alertdialog',{name:'Confirm test action'}).getByRole('button',{name:'Continue',exact:true}).click();
  await expect(panel.getByRole('table')).toContainText('activated');
  await expect(panel).toContainText('without first building an App, MQTT client or WebRTC Viewer');
  await expect(panel.getByRole('button',{name:/End test session|Stop session|Disconnect all/i})).toHaveCount(0);
  await expect(panel.getByRole('button',{name:'Unsubscribe',exact:true})).toBeVisible();
  await expect(panel.getByRole('button',{name:'Disconnect',exact:true})).toBeVisible();
  await expect(panel.locator('#test-lab-product-id')).toContainText(product);
  await expect(panel.locator('[role="tab"] i[aria-hidden="true"]')).toHaveCount(3);
  await expect(panel.getByRole('heading',{name:'Device test workspace',exact:true})).toBeVisible();
  await expect(panel.getByRole('status').filter({hasText:'No live connection has been made'})).toHaveCount(1);
  await expect(panel.getByRole('button',{name:'Connect',exact:true})).toBeDisabled();
  await panel.getByRole('textbox',{name:'JSON payload'}).fill('{"command":"example"}');
  await panel.getByRole('button',{name:'Validate locally — no request sent'}).click();
  await expect(panel.locator('#test-lab-validation-help')).toContainText('publish topic format');
  await expect(panel.locator('#test-lab-validation-help')).toContainText('no messages are published');
  await expect(panel).toContainText('local_validation: passed');
  await expect(panel.locator('.test-lab-events')).toHaveCSS('font-family', /monospace/);
  await expect(panel.locator('pre').first()).toHaveCSS('font-family', /monospace/);
  expect(liveWrites).toBe(0);
  await panel.getByRole('tab',{name:'Shadow',exact:true}).click();
  await expect(panel.locator('#test-lab-validation-help')).toContainText('Shadow name format');
  await expect(panel.getByRole('button',{name:'Read',exact:true})).toBeDisabled();
  await panel.getByRole('tab',{name:'WebRTC',exact:true}).click();
  await expect(panel).toContainText('No decoded media received');
  const videoBox = await panel.locator('video').boundingBox();
  expect(videoBox.width / videoBox.height).toBeCloseTo(16 / 9, 1);
  await expect(panel.locator('.test-lab-video-metric')).toHaveCount(4);
  await expect(panel.getByRole('button',{name:'Reload devices & access',exact:true})).toBeVisible();
  const download=page.waitForEvent('download');await panel.getByRole('button',{name:'Download diagnostic report'}).click();
  expect((await download).suggestedFilename()).toBe('cloud-test-lab-report.json');
  await info.attach('test-lab-console',{body:await panel.screenshot(),contentType:'image/png'});
  await panel.getByRole('button',{name:'Unbind',exact:true}).click();
  await panel.getByRole('alertdialog',{name:'Confirm test action'}).getByRole('button',{name:'Cancel action',exact:true}).click();
  await expect(panel.getByRole('button',{name:'Unbind',exact:true})).toBeVisible();
  await panel.getByRole('button',{name:'Unbind',exact:true}).click();
  await panel.getByRole('alertdialog',{name:'Confirm test action'}).getByRole('button',{name:'Continue',exact:true}).click();
  await expect(panel).toContainText('No bound test devices');
  await expect(panel.getByRole('button',{name:'Start playback',exact:true})).toBeDisabled();
  await panel.getByRole('button',{name:'Bind device',exact:true}).click();
  await panel.getByRole('combobox',{name:'Unbound test device'}).selectOption(device);
  await panel.getByRole('button',{name:'Confirm bind',exact:true}).click();
  await panel.getByRole('alertdialog',{name:'Confirm test action'}).getByRole('button',{name:'Continue',exact:true}).click();
  await expect(panel.getByRole('button',{name:'Unbind',exact:true})).toBeVisible();
  expect(claims).toBe(2);
  await page.route('**/test-lab/sessions',route=>route.fulfill({json:{id:'99999999-9999-4999-8999-999999999999',expires_at:new Date(Date.now()+300000).toISOString()}}));
  await page.route('**/test-lab/sessions/*/shadow',route=>route.fulfill({status:404}));
  runtimeReady=true;
  await panel.getByRole('button',{name:'Reload devices & access',exact:true}).click();
  await panel.getByRole('tab',{name:'Shadow',exact:true}).click();
  await panel.getByRole('textbox',{name:'Shadow name (empty = unnamed)'}).fill('missing-shadow');
  await panel.getByRole('button',{name:'Read',exact:true}).click();
  await expect(panel.getByRole('status').filter({hasText:'This Shadow does not exist yet'})).toBeVisible();
  await expect(panel).not.toContainText('Operation failed (HTTP 404)');
  await expect(panel).toContainText('shadow_get: not_found');
  await expect(panel.getByRole('button',{name:'Read',exact:true})).toBeEnabled();
  await panel.getByRole('tab',{name:'WebRTC',exact:true}).click();
  await expect(panel.getByRole('button',{name:'Start playback',exact:true})).toBeEnabled();
  await panel.getByRole('button',{name:'Start playback',exact:true}).click();
  const liveConfirm=panel.getByRole('alertdialog',{name:'Confirm live test action'});
  await expect(liveConfirm).toContainText('camera-1');
  expect(liveWrites).toBe(0);
  await liveConfirm.getByRole('button',{name:'Cancel action',exact:true}).click();
  expect(liveWrites).toBe(0);
  await panel.getByRole('button',{name:'Start playback',exact:true}).click();
  await liveConfirm.getByRole('button',{name:'Continue',exact:true}).click();
  await expect(panel).toContainText('webrtc_start: failed');
  expect(liveWrites).toBe(1);
  // Product changes clear sensitive in-memory downloads instead of persisting them.
  await panel.getByRole('combobox',{name:'Product',exact:true}).selectOption('');
  await expect(panel.getByRole('region',{name:'Device credentials ready'})).toHaveCount(0);
  await expect(panel.getByRole('region',{name:'Provision key ready'})).toHaveCount(0);
});
