-- Schema documentation metadata. Keep changes beside schema changes.
CREATE TABLE IF NOT EXISTS schema_metadata (
  object_kind TEXT NOT NULL CHECK (object_kind IN ('group','table','column','logical_ref')),
  schema_name TEXT NOT NULL DEFAULT 'main',
  object_name TEXT NOT NULL,
  meta_version INTEGER NOT NULL DEFAULT 1 CHECK (meta_version = 1),
  details TEXT NOT NULL CHECK (json_valid(details)),
  PRIMARY KEY (object_kind, schema_name, object_name)
);
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('group','main','Administrator sessions and integration settings','{"purpose":"Global-user sessions and integration configuration.","scenario":"Used for authenticated Admin sessions and integration settings; upstream identity is owned by Account Manager.","service":"Cloud Admin"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('group','main','Batch jobs','{"purpose":"Batch jobs, per-item processing, action receipts, and provisioning or OTA scope previews.","scenario":"Used to submit bulk device work, retry failed items, or preview an operation scope.","service":"Cloud Admin"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('group','main','Device operations view','{"purpose":"Administrative device and operation views, readiness layers, and audit events.","scenario":"Used to show device details, investigate operation status, or record administrative actions.","service":"Cloud Admin"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('group','main','Schema versions','{"purpose":"Applied Cloud Admin local database migrations.","scenario":"Checked at service startup or upgrade.","service":"Cloud Admin"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('group','main','Support ticket activity','{"purpose":"Support ticket activity.","scenario":"Used by the related service workflow.","service":"Cloud Admin"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('table','main','audit_events','{"group":"Device operations view","purpose":"Actors, targets, outcomes, and request IDs for administrative actions.","scenario":"Records an audit trail after an administrator performs a sensitive action.","service":"Cloud Admin","source":"repos/rtk_cloud_admin/internal/store/store.go"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','audit_events.id','{"critical":"key","description":"Primary key of audit_events."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('table','main','batch_job_action_receipts','{"group":"Batch jobs","purpose":"Receipts for batch-job state transitions and action keys.","scenario":"Makes pause, resume, and cancel actions idempotent.","service":"Cloud Admin","source":"repos/rtk_cloud_admin/internal/store/store.go"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','batch_job_action_receipts.job_id','{"critical":"key","description":"Part of composite primary key (job_id, action_key); references batch_jobs.id."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','batch_job_action_receipts.action_key','{"critical":"key","description":"Part of composite primary key (job_id, action_key)."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','batch_job_action_receipts.from_state','{"description":"Current lifecycle state of batch_job_action_receipts.","semantic_kind":"state"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','batch_job_action_receipts.to_state','{"description":"Current lifecycle state of batch_job_action_receipts.","semantic_kind":"state"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('table','main','batch_job_items','{"group":"Batch jobs","purpose":"Position, state, error, and retryability of each device or item in a batch.","scenario":"Used for per-item provisioning, failure retry, and paginated progress queries.","service":"Cloud Admin","source":"repos/rtk_cloud_admin/internal/store/store.go"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','batch_job_items.job_id','{"critical":"key","description":"Part of composite primary key (job_id, item_key); references batch_jobs.id."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','batch_job_items.item_key','{"critical":"key","description":"Part of composite primary key (job_id, item_key)."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','batch_job_items.state','{"description":"Current lifecycle state of batch_job_items.","semantic_kind":"state"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('table','main','batch_jobs','{"group":"Batch jobs","purpose":"Organization batch-job types, scopes, progress, leases, and checkpoints.","scenario":"Used to schedule, execute, and recover bulk provisioning or administration work.","service":"Cloud Admin","source":"repos/rtk_cloud_admin/internal/store/store.go"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','batch_jobs.id','{"critical":"key","description":"Primary key of batch_jobs."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','batch_jobs.state','{"description":"Current lifecycle state of batch_jobs.","semantic_kind":"state"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','batch_jobs.authorization_status','{"description":"Current lifecycle state of batch_jobs.","semantic_kind":"state"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('table','main','devices','{"group":"Device operations view","purpose":"Device, organization, status, and Video Cloud ID shown in the admin interface.","scenario":"Used for listing, searching, and viewing device state; it is not an upstream master-data foreign key.","service":"Cloud Admin","source":"repos/rtk_cloud_admin/internal/store/store.go"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','devices.id','{"critical":"key","description":"Primary key of devices."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','devices.status','{"description":"Current lifecycle state of devices.","semantic_kind":"state"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('table','main','integration_settings','{"group":"Administrator sessions and integration settings","purpose":"Integration key/value settings, sources, and update times.","scenario":"Defined in schema for integration configuration; no direct non-DDL read or write path was found.","service":"Cloud Admin","source":"repos/rtk_cloud_admin/internal/store/store.go"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','integration_settings.key','{"critical":"key","description":"Primary key of integration_settings."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('table','main','operations','{"group":"Device operations view","purpose":"Device-operation summaries, organizations, status, and upstream operation IDs.","scenario":"Used to display recent operations and outcomes in the admin console.","service":"Cloud Admin","source":"repos/rtk_cloud_admin/internal/store/store.go"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','operations.id','{"critical":"key","description":"Primary key of operations."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','operations.state','{"description":"Current lifecycle state of operations.","semantic_kind":"state"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','operations.upstream_state','{"description":"Current lifecycle state of operations.","semantic_kind":"state"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('table','main','ota_scope_previews','{"group":"Batch jobs","purpose":"OTA target scopes, hashes, match counts, and data freshness.","scenario":"Used to preview affected devices before dispatch.","service":"Cloud Admin","source":"repos/rtk_cloud_admin/internal/store/store.go"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','ota_scope_previews.id','{"critical":"key","description":"Primary key of ota_scope_previews."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','ota_scope_previews.target_count','{"description":"Count of matching records.","semantic_kind":"count"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','ota_scope_previews.matched_count','{"description":"Count of matching records.","semantic_kind":"count"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','ota_scope_previews.excluded_count','{"description":"Count of matching records.","semantic_kind":"count"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('table','main','provisioning_sources','{"group":"Batch jobs","purpose":"Imported provisioning files, checksums, products, and device-ID lists.","scenario":"Used when uploading factory or device lists for bulk provisioning.","service":"Cloud Admin","source":"repos/rtk_cloud_admin/internal/store/store.go"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','provisioning_sources.id','{"critical":"key","description":"Primary key of provisioning_sources."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','provisioning_sources.row_count','{"description":"Count of matching records.","semantic_kind":"count"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('table','main','readiness_facts','{"group":"Device operations view","purpose":"Per-device readiness-layer states, errors, and operations.","scenario":"Defined in schema for layered readiness projection; no direct non-DDL read or write path was found.","service":"Cloud Admin","source":"repos/rtk_cloud_admin/internal/store/store.go"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','readiness_facts.id','{"critical":"key","description":"Primary key of readiness_facts."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','readiness_facts.state','{"description":"Current lifecycle state of readiness_facts.","semantic_kind":"state"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('table','main','schema_migrations','{"group":"Schema versions","purpose":"Applied Cloud Admin SQLite migration versions and names.","scenario":"Checked at startup or upgrade to establish database structure.","service":"Cloud Admin","source":"repos/rtk_cloud_admin/internal/store/store.go"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','schema_migrations.version','{"critical":"key","description":"Primary key of schema_migrations."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('table','main','sessions','{"group":"Administrator sessions and integration settings","purpose":"Admin or upstream session principals, tokens, organizations, and expiry.","scenario":"Used on sign-in, refresh, and active-organization switches.","service":"Cloud Admin","source":"repos/rtk_cloud_admin/internal/store/store.go"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','sessions.id','{"critical":"key","description":"Primary key of sessions."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('table','main','support_ticket_read_markers','{"group":"Support ticket activity","purpose":"Per-actor support ticket read markers.","scenario":"Tracks which tickets an administrator has viewed.","service":"Cloud Admin","source":"repos/rtk_cloud_admin/internal/store/store.go"}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','support_ticket_read_markers.actor_id','{"critical":"key","description":"Primary key of support_ticket_read_markers."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','support_ticket_read_markers.scope_id','{"critical":"key","description":"Primary key of support_ticket_read_markers."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
INSERT INTO schema_metadata (object_kind,schema_name,object_name,details) VALUES ('column','main','support_ticket_read_markers.ticket_id','{"critical":"key","description":"Primary key of support_ticket_read_markers."}') ON CONFLICT (object_kind,schema_name,object_name) DO UPDATE SET details=excluded.details;
