// Research-backed proposal only. This catalog does not configure Billing plans.
// Source inventory and rationale: docs/service-pricing-research.md.
export const pricingResearchDate = '2026-09-06';
export const pricingGroups = ['All services', 'IoT and messaging', 'Live video', 'Storage and delivery', 'Device operations'];
export const pricingSources = {
  iot: { name: 'AWS IoT Core', url: 'https://aws.amazon.com/iot-core/pricing/' },
  video: { name: 'AWS Kinesis Video Streams', url: 'https://aws.amazon.com/kinesis/video-streams/pricing/' },
  r2: { name: 'Cloudflare R2', url: 'https://developers.cloudflare.com/r2/pricing/' },
  akamai: { name: 'Akamai Cloud', url: 'https://www.akamai.com/cloud/pricing' },
  jobs: { name: 'AWS IoT Device Management', url: 'https://aws.amazon.com/iot-device-management/pricing/' },
  logs: { name: 'Amazon CloudWatch', url: 'https://aws.amazon.com/cloudwatch/pricing/' },
  api: { name: 'Amazon API Gateway', url: 'https://aws.amazon.com/api-gateway/pricing/' },
};

export const servicePricing = [
  { id: 'mqtt-publish', group: 'IoT and messaging', name: 'MQTT publishes', description: 'Messages accepted from devices or applications.', price: 30, unit: '1 million messages', readiness: 'Usage meter exists', rule: 'Count each accepted publish once. Payload traffic is included; no separate MQTT bandwidth fee.', source: 'iot', benchmark: 'US$1 / million 5 KB message units', comparison: 'Ireland, first billion units. RTK proposes raw message counts, so large-payload prices are not directly equivalent.' },
  { id: 'mqtt-delivery', group: 'IoT and messaging', name: 'MQTT deliveries', description: 'Messages delivered to subscribers.', price: 30, unit: '1 million deliveries', readiness: 'Usage meter exists', rule: 'One publish to five subscribers counts as one publish plus five deliveries. Each broker delivery is counted.', source: 'iot', benchmark: 'US$1 / million 5 KB message units', comparison: 'Ireland, first billion units. AWS also charges publish and delivery separately.' },
  { id: 'shadow', group: 'IoT and messaging', name: 'IoT Shadow', description: 'Read, update, delete and list device state.', price: 40, unit: '1 million operation units', readiness: 'Metering pending', rule: 'Successful operations, rounded up in 1 KiB record or response units. MQTT transport, when used, is counted separately.', source: 'iot', benchmark: 'US$1.25 / million 1 KB operation units', comparison: 'Canada Central example. A 1.5 KiB state operation would use two proposed RTK units.' },
  { id: 'turn', group: 'Live video', name: 'WebRTC TURN relay', description: 'Live media sent through the cloud relay.', price: 1, unit: 'GiB delivered', readiness: 'Metering pending', rule: 'Count bytes sent by TURN to recipients, including each viewer. Relay processing is included. No extra minute or download charge on these bytes. Direct P2P media is free.', source: 'video', benchmark: 'US$0.12 / 1,000 TURN minutes + internet transfer', comparison: 'US East. AWS also charges signaling channels and messages. Different unit: our proposal follows delivered bytes; Akamai transfer costs inform the rate.' },
  { id: 'storage', group: 'Storage and delivery', name: 'Video and firmware storage', description: 'Stored clips, snapshots and firmware artifacts.', price: 1, unit: 'GiB-month', readiness: 'Metering pending', rule: 'Average stored bytes over time, prorated by retention. A 10 GiB object kept for 15 of 30 days uses 5 GiB-month. Logs use the separate retention rate.', source: 'r2', benchmark: 'US$0.015 / GB-month, Standard', comparison: 'Akamai lists US$0.02 / GB-month. Proposal includes service operations; provider minimums and free tiers differ.' },
  { id: 'object-write', group: 'Storage and delivery', name: 'Object writes', description: 'Upload clips, snapshots and firmware objects.', price: 150, unit: '1 million write operations', readiness: 'Metering pending', rule: 'Count successful object writes and multipart part writes. A multipart completion is one further write. Upload bandwidth is included.', source: 'r2', benchmark: 'US$4.50 / million Class A operations', comparison: 'Standard tier. R2 Class A covers more operations than uploads; this is a write-cost benchmark.' },
  { id: 'object-read', group: 'Storage and delivery', name: 'Object reads', description: 'Read media or firmware from storage.', price: 15, unit: '1 million read operations', readiness: 'Metering pending', rule: 'Count successful object GET and HEAD requests; each range request is a read. Delivered bytes use the download rate below.', source: 'r2', benchmark: 'US$0.36 / million Class B operations', comparison: 'Standard tier. R2 internet egress is free; RTK proposes a separate managed delivery charge.' },
  { id: 'download', group: 'Storage and delivery', name: 'Media and firmware downloads', description: 'Cloud-to-device or cloud-to-app file delivery.', price: 1, unit: 'GiB delivered', readiness: 'Metering pending', rule: 'Count outgoing file bytes once, including retries and multiple recipients. Excludes TURN and MQTT traffic. Inbound transfer is included.', source: 'akamai', benchmark: 'US$0.005 / GB egress over allowance', comparison: 'Core regions; distributed regions list US$0.01 / GB. Object Storage includes 1 TB egress monthly. RTK price includes managed delivery overhead.' },
  { id: 'ota', group: 'Device operations', name: 'Firmware OTA tasks', description: 'Deliver an update task to a target device.', price: 100, unit: '1,000 device tasks', readiness: 'Metering pending', rule: 'One campaign targeting 1,000 devices is 1,000 tasks. Count a device task when first dispatched; retries of that task add no task fee. Storage, object reads and file delivery are separate.', source: 'jobs', benchmark: 'US$0.003 / remote action', comparison: 'AWS Device Jobs example, first 250,000 actions. Roughly NT$96 / 1,000 actions at the planning conversion.' },
  { id: 'log-ingest', group: 'Device operations', name: 'Device and application logs', description: 'Ingest runtime logs for diagnosis.', price: 10, unit: 'GiB ingested', readiness: 'Usage totals exist', rule: 'Use accepted, uncompressed log bytes including metadata. Retention is charged separately. MQTT transport, when used, retains its message fee.', source: 'logs', benchmark: 'US$0.50 / GB ingested', comparison: 'US East example, Standard logs entry tier. RTK already records log ingestion totals; invoice integration remains to be qualified.' },
  { id: 'log-retention', group: 'Device operations', name: 'Log retention', description: 'Keep runtime logs available for review.', price: 1, unit: 'GiB-month', readiness: 'Usage totals exist', rule: 'Use recorded log bytes × configured retention days / 30. This proposal follows the existing retention estimate, not compressed archive size.', source: 'logs', benchmark: 'US$0.03 / GB-month archived', comparison: 'US East example. CloudWatch uses compressed archive bytes, so the byte basis differs from this RTK proposal.' },
  { id: 'api', group: 'Device operations', name: 'Application API requests', description: 'Other device and application data API calls.', price: 30, unit: '1 million requests', readiness: 'Metering pending', rule: 'Count successful data API requests only. Excludes Shadow, WebRTC signaling, OTA task dispatch and object operations already covered above. Console administration and authentication are included.', source: 'api', benchmark: 'US$1 / million HTTP API calls', comparison: 'AWS example, first 300 million monthly calls. Backend processing and data transfer may be additional on AWS.' },
];
